name: Action_Kernel


on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env

      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.kernel_name }}" "KERNEL_NAME config"
          required "${{ steps.config.outputs.branch_name }}" "BRANCH_NAME config"
          required "${{ steps.config.outputs.kernel_url }}" "KERNEL_URL config"
 
      - name: Git kernel
        run: |
          git clone "${{ steps.config.outputs.kernel_url }}" -b "${{ steps.config.outputs.branch_name }}" --depth=1 kernel

      - name: Initializing Environment
        run: |
          sudo apt install -y wget bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          
      - name: Download gcc 
        run: |
           cd $GITHUB_WORKSPACE/kernel
           mkdir tool
           git clone https://github.com/Aquarius223/google_clang_kernel_compiler.git --depth=1 tool/clang         
           wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz
           wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-x86_64-arm-none-eabi.tar.xz
           tar -xvJf gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz -C tool
           tar -xvJf gcc-arm-10.3-2021.07-x86_64-arm-none-eabi.tar.xz -C tool
           mv tool/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu tool/aarch
           mv tool/gcc-arm-10.3-2021.07-x86_64-arm-none-eabi tool/arm

      - name: Make kernel
        run: |
          sudo mv build.sh $GITHUB_WORKSPACE/kernel
          cd $GITHUB_WORKSPACE/kernel
          bash ./build.sh

      - name: Upload boot to WeTransfer
        run: |
              cd $GITHUB_WORKSPACE/kernel/out/arch/arm64/boot
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet Image.gz-dtb
